// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The env() helper will now safely find DATABASE_URL
    // because dotenv loaded it into process.env right above.
    url: env("DATABASE_URL"),
  },
});
